Update pdm locking

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -106,6 +106,8 @@ jobs:
           uv-dependency-install-flags: "--all-extras --group tests"
       - name: Run tests
         run: |
+          # Warm up the speed tests, allowing failure
+          uv run pytest tests/integration/database/test_integration_speed.py || true
           uv run pytest -r a -v src tests --doctest-modules --cov=src --cov-report=term-missing --cov-report=xml
           uv run coverage report
       - name: Upload coverage reports to Codecov with GitHub Action
@@ -275,7 +277,8 @@ jobs:
         # Required for building the locked version of the package
         # with pdm-build-locked (see pyproject.toml)
         run: |
-          pdm lock --group :all --strategy inherit_metadata
+          pdm lock --group :all --strategy inherit_metadata --python="<3.13"
+          pdm lock --group :all  --python=">=3.13" --append
       - name: Build package
         run: |
           uv build
